# Generated by Django 4.2.4 on 2023-09-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
    ]
