# Generated by Django 4.2.4 on 2023-09-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
    ]
